#!/usr/bin/env python3
# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Enumerate the source files this repository is responsible for.

Authority boundary: this module decides *which files the modularity rules
apply to* — nothing else. It does not measure them, does not know the cap, and
holds no exemptions.

Owning milestone: M0 (WP-M0-09).

Two questions, one answer each.

**Which files are ours?** Everything Git tracks plus everything it would track
(`--cached --others --exclude-standard`), restricted to the roots this
repository authors and to the extensions `code_lines.LANGUAGES` names. A
component that has been written but not yet committed is exactly the material a
discipline gate exists to catch, so untracked-and-not-ignored counts. Outside a
Git checkout the walk falls back to the filesystem with the same skip list.

**Which of those are generated?** A generated file is the output of a rule
somewhere else; splitting it edits the wrong artifact and the split is undone
by the next regeneration. Generated files are therefore *detected*, never
exempted by hand: an exemption entry would rot the moment the generator changes
its output layout.

Stdlib only. Read-only.
"""

from __future__ import annotations

import os
import subprocess

import code_lines

__all__ = [
    "GENERATED_MARKER",
    "SKIP_DIRS",
    "SOURCE_ROOTS",
    "is_generated",
    "source_files",
]

#: The roots this repository authors. Everything outside them is either
#: reference material (`_refs`), machine-local state, or a build tree.
SOURCE_ROOTS = (
    "build-logic",
    "taffy-core",
    "test-fixtures",
    "tools",
    "website",
)

#: Directory names that never hold source this repository is responsible for.
#: Every name here is also gitignored; the list exists so the filesystem
#: fallback outside a Git checkout reaches the same answer as `git ls-files`.
SKIP_DIRS = {
    ".git",
    ".gradle",
    ".kotlin",
    ".next",
    ".taffy",
    "__pycache__",
    "_refs",
    "build",
    "dist",
    "node_modules",
    "out",
    "target",
}

#: The marker every generator in this repository writes into its first lines.
#: `taffy-core/contracts/bip/codegen/generate.py` emits it; so does every other generator,
#: by rule — a generator that does not mark its output is a defect in the
#: generator, not a reason to add an exemption here.
GENERATED_MARKER = "@generated"

#: How far into a file the marker is looked for. Far enough to sit under a
#: licence header or a shebang, near enough that the word appearing in a
#: paragraph halfway down a hand-written file cannot silence the gate.
# Six of these lines are now the licence notice, which sits above the marker
# in every generated file (decision 0205). Ten left three lines of slack over
# a window that has to hold a shebang, the notice and whatever a generator
# says about itself before it says it is generated; sixteen leaves room for
# the next thing that goes above the marker, and nothing is misread as
# generated by looking further, because the marker is the whole test.
_MARKER_WINDOW = 16


def is_generated(path: str, repo_root: str) -> bool:
    """True when `path` is the output of a generator rather than a source file.

    Two independent signals, either sufficient:

      1. a `generated` path segment — the convention this repository uses for
         whole output trees (`taffy-core/contracts/bip/rust/bip-types/src/generated/`,
         `taffy-core/contracts/bip/generated/`);
      2. the `@generated` marker in the file's opening lines, which is what a
         generator writing into a hand-written tree leaves behind.
    """
    relative = os.path.relpath(path, repo_root).replace(os.sep, "/")
    if "generated" in relative.split("/"):
        return True
    try:
        with open(path, encoding="utf-8", errors="replace") as handle:
            for index, line in enumerate(handle):
                if index >= _MARKER_WINDOW:
                    return False
                if GENERATED_MARKER in line:
                    return True
    except OSError:
        return False
    return False


def _git_listing(repo_root: str) -> list[str] | None:
    try:
        result = subprocess.run(
            ["git", "-C", repo_root, "ls-files", "--cached", "--others", "--exclude-standard"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return [line for line in result.stdout.splitlines() if line]


def _walk_listing(repo_root: str) -> list[str]:
    found: list[str] = []
    for root in SOURCE_ROOTS:
        base = os.path.join(repo_root, root)
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for name in filenames:
                full = os.path.join(dirpath, name)
                found.append(os.path.relpath(full, repo_root).replace(os.sep, "/"))
    return found


def _under_source_root(relative: str) -> bool:
    return any(relative == root or relative.startswith(root + "/") for root in SOURCE_ROOTS)


def source_files(repo_root: str) -> list[str]:
    """Repository-relative paths of every source file the rules apply to.

    Sorted, deduplicated, and already filtered to the source roots, the known
    extensions, and the skip list. Generated files are *included* — the caller
    asks `is_generated` about them, because some callers (the include-direction
    rules) care about generated output and some (the size cap) do not.
    """
    listing = _git_listing(repo_root)
    if listing is None:
        listing = _walk_listing(repo_root)

    keep: set[str] = set()
    for relative in listing:
        if not _under_source_root(relative):
            continue
        if set(relative.split("/")) & SKIP_DIRS:
            continue
        if code_lines.language_for(relative) is None:
            continue
        if not os.path.isfile(os.path.join(repo_root, relative)):
            continue
        keep.add(relative)
    return sorted(keep)
