#!/usr/bin/env python3
# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Every licence a vendored component names is a file this repository ships.

``NOTICE`` section 2 tells a reader that the licences are "recorded beside
each vendored component, under taffy-core/third_party/ and each component's
own vendor directory". Nothing checked that, and it was not true.

``taffy-core/third_party/cpython/README.chromium`` declared
``License File: src/LICENSE`` while ``/taffy-core/third_party/cpython/src/``
is gitignored — the interpreter source is fetched, not committed. The Python
Software Foundation text was therefore present on the machine that had built
CPython and absent from every clone, including the one a published repository
would be. A build was unaffected, every lane was green, and the only symptom
was a promise in ``NOTICE`` that a reader could not follow.

So the rule is about **trackedness**, not existence: a licence file that is
only on this disk is not a notice anyone else receives. Checking existence
would have passed over exactly the case that happened.

Two things are deliberately out of scope. Whether the named text is the right
licence for the component is a reading, not a property of the tree, and it
belongs to the vendoring review that ``OWNERS`` describes. And the credits
page a built artifact carries is generated by Chromium's own
``tools/licenses/licenses.py`` from this same metadata, on the far side of
``./tools/chromium/build``; this gate is what a host can prove before that.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile

#: Where a vendored component's Chromium metadata lives.
THIRD_PARTY = "taffy-core/third_party"

#: The metadata file Chromium's own generator reads.
README = "README.chromium"

#: Values that name no file and are not a defect. Chromium's own trees use
#: these for a component whose licence is stated inline or which ships none.
NOT_A_PATH = frozenset({"NOT_SHIPPED", "NONE", "N/A"})


def stanzas(text: str) -> list[dict[str, tuple[int, str]]]:
    """Split a README.chromium into its metadata stanzas.

    One file may declare several components — ``dagger`` declares fifteen —
    and each ``Name:`` starts a new one. Values keep their 1-based line
    number so a finding can point at the line rather than at the file.
    """
    found: list[dict[str, tuple[int, str]]] = []
    current: dict[str, tuple[int, str]] = {}
    for number, line in enumerate(text.splitlines(), start=1):
        if line.startswith("#"):
            continue
        if ":" not in line:
            continue
        field, _, value = line.partition(":")
        field = field.strip()
        value = value.strip()
        if field == "Name":
            if current:
                found.append(current)
            current = {}
        if field in ("Name", "License", "License File", "Shipped"):
            current[field] = (number, value)
    if current:
        found.append(current)
    return found


def tracked_paths(repo_root: str) -> set[str]:
    """Every path Git tracks, as repository-relative POSIX strings."""
    listing = subprocess.run(
        ["git", "-C", repo_root, "ls-files", "-z"],
        capture_output=True,
        check=True,
        text=True,
    ).stdout
    return {entry for entry in listing.split("\0") if entry}


def readme_files(repo_root: str) -> list[str]:
    """Every ``README.chromium`` under the first-party third-party root."""
    base = os.path.join(repo_root, THIRD_PARTY)
    if not os.path.isdir(base):
        return []
    found = []
    for name in sorted(os.listdir(base)):
        candidate = os.path.join(base, name, README)
        if os.path.isfile(candidate):
            found.append(os.path.relpath(candidate, repo_root).replace(os.sep, "/"))
    return found


def findings_for(
    relative_readme: str, text: str, tracked: set[str]
) -> list[str]:
    """Findings for one README.chromium, given the tracked-path set."""
    directory = os.path.dirname(relative_readme)
    findings: list[str] = []
    for stanza in stanzas(text):
        name = stanza.get("Name", (0, "?"))[1]
        if "License File" not in stanza:
            line = stanza.get("Name", (0, ""))[0]
            findings.append(
                f"{relative_readme}:{line}: {name} declares no `License File:`, "
                "so nothing says where its terms are"
            )
            continue
        line, value = stanza["License File"]
        for piece in (part.strip() for part in value.split(",")):
            if not piece or piece in NOT_A_PATH:
                continue
            target = os.path.normpath(os.path.join(directory, piece)).replace(os.sep, "/")
            if target in tracked:
                continue
            on_disk = " (it is on this disk, but untracked)" if _exists(target) else ""
            findings.append(
                f"{relative_readme}:{line}: {name} names licence file {piece}, "
                f"which this repository does not track{on_disk}"
            )
    return findings


def _exists(relative: str) -> bool:
    return os.path.exists(os.path.join(_ROOT[0], relative))


#: Set by `run` so `_exists` can answer without threading the root through
#: `findings_for`, which the self-test calls directly with its own fixtures.
_ROOT = [""]


def run(repo_root: str) -> list[str]:
    _ROOT[0] = repo_root
    tracked = tracked_paths(repo_root)
    findings: list[str] = []
    for relative in readme_files(repo_root):
        with open(os.path.join(repo_root, relative), encoding="utf-8") as handle:
            findings.extend(findings_for(relative, handle.read(), tracked))
    return findings


FIXTURE = """# a comment line that is not metadata
Name: Example
License: MIT
License File: vendor/example.MIT.txt
Shipped: yes

Name: Second
License: Apache-2.0
License File: LICENSE
Shipped: no
"""


def self_test() -> list[str]:
    """Fixtures for each way this can fail, including the one that happened."""
    failures: list[str] = []

    parsed = stanzas(FIXTURE)
    if len(parsed) != 2:
        failures.append(f"two stanzas expected, parsed {len(parsed)}")
    elif parsed[1]["License File"][1] != "LICENSE":
        failures.append("the second stanza's License File was not read")

    readme = f"{THIRD_PARTY}/example/{README}"
    both = {
        f"{THIRD_PARTY}/example/vendor/example.MIT.txt",
        f"{THIRD_PARTY}/example/LICENSE",
    }
    with tempfile.TemporaryDirectory(prefix="taffy-third-party-notices-") as root:
        _ROOT[0] = root
        if findings_for(readme, FIXTURE, both):
            failures.append("a README whose licence files are all tracked did not pass")

        # The case that happened: the file is on disk and not tracked.
        untracked = os.path.join(root, THIRD_PARTY, "example")
        os.makedirs(untracked, exist_ok=True)
        with open(os.path.join(untracked, "LICENSE"), "w", encoding="utf-8") as handle:
            handle.write("text\n")
        missing = {f"{THIRD_PARTY}/example/vendor/example.MIT.txt"}
        reported = findings_for(readme, FIXTURE, missing)
        if not any("does not track" in finding for finding in reported):
            failures.append("an untracked licence file did not fail")
        if not any("on this disk, but untracked" in finding for finding in reported):
            failures.append("an untracked-but-present licence file was not distinguished")

        absent = findings_for(readme, FIXTURE.replace("License File: LICENSE\n", ""), both)
        if not any("declares no `License File:`" in finding for finding in absent):
            failures.append("a stanza with no License File did not fail")

        excused = findings_for(
            readme, FIXTURE.replace("License File: LICENSE", "License File: NOT_SHIPPED"), both
        )
        if excused:
            failures.append("NOT_SHIPPED was treated as a path")

    return failures


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--self-test", action="store_true", help="exercise the fixtures and exit"
    )
    parser.add_argument("root", nargs="?", default=".", help="repository root")
    args = parser.parse_args(argv)

    failures = self_test()
    for failure in failures:
        print(f"third-party notices self-test: {failure}", file=sys.stderr)
    if failures:
        return 1
    if args.self_test:
        print("third-party notices self-test: all fixtures passed")
        return 0

    repo_root = os.path.abspath(args.root)
    findings = run(repo_root)
    for finding in findings:
        print(f"third-party notices: {finding}", file=sys.stderr)
    if findings:
        return 1

    readmes = readme_files(repo_root)
    declared = sum(len(stanzas(open(os.path.join(repo_root, r), encoding="utf-8").read()))
                   for r in readmes)
    print(
        f"third-party notices: {declared} component(s) across {len(readmes)} "
        f"{README} file(s) name a tracked licence file"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
