// Copyright (c) 2026 Matterward Labs Private Limited.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { ArrowRight, ArrowUpRight, Check, KeyRound, Smartphone } from "lucide-react";
import { withBasePath } from "@/lib/base-path";
import directory from "@/lib/provider-directory.json";
export function ConnectionPreview() {
  return <section className="provider-choice-section" aria-labelledby="provider-choice-title"><div className="container-site provider-choice-grid"><div className="provider-connection"><div className="preview-window-bar"><span><i /><i /><i /></span><strong>Your AI connections</strong><KeyRound size={15} /></div><div className="connection-provider"><img className="mono-logo" src={withBasePath("/providers/openai.svg")} width={30} height={30} alt="" /><div><strong>OpenAI</strong><span>Your API key</span></div><span className="connection-example">Example</span></div><div className="connection-provider"><img src={withBasePath("/providers/anthropic.svg")} width={30} height={30} alt="" /><div><strong>Anthropic</strong><span>Claude models</span></div><Check size={17} /></div><div className="connection-provider"><img src={withBasePath("/providers/google-ai-studio.svg")} width={30} height={30} alt="" /><div><strong>Google AI Studio</strong><span>Gemini models</span></div><Check size={17} /></div><div className="connection-route"><Smartphone size={22} /><span>Your phone</span><ArrowRight size={18} /><KeyRound size={22} /><span>Your provider</span></div><p>Connection preview. No credentials are collected here.</p></div><div className="provider-choice-copy"><h2 id="provider-choice-title">Choose the AI<br />behind Taffy.</h2><p>Connect your own key or an eligible provider plan. Taffy stays the assistant in your browser; you choose which provider handles its model requests.</p><p>Requests go directly from your phone to that provider. TaffyGo is free. Any provider charges remain between you and the provider.</p><div className="provider-choice-counts"><span><strong>{directory.providers.length}</strong> providers</span><span><strong>{directory.providers.reduce((sum,p)=>sum+p.models.length,0)}</strong> model entries</span></div><a className="text-link" href={withBasePath("/providers/")}>Find your provider and models <ArrowUpRight size={16} /></a></div></div></section>;
}
