// Copyright (c) 2026 Matterward Labs Private Limited.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

"use client";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Check, FileSpreadsheet, FileText, LockKeyhole } from "lucide-react";
import { withBasePath } from "@/lib/base-path";
export function LocalToolsPreview() {
  const [kind,setKind]=useState("document");
  return <section className="container-site local-tools-section" aria-labelledby="local-tools-title"><div className="local-tools-copy"><span className="technology-label"><img src={withBasePath("/providers/python.svg")} width={25} height={25} alt="Python" /> Inside the engine</span><h2 id="local-tools-title">On-device tools.<br />Python included.</h2><p>Some tasks need a file, not another chat message. TaffyGo integrates Python for registered document and spreadsheet builders, alongside its native file tools.</p><p>The interpreter is part of the Android build. A separate worker runs selected tools with limits on time, memory, and output.</p><a className="text-link" href={withBasePath("/technology/")}>Explore the runtime and its status <ArrowUpRight size={16} /></a></div><div className="local-tools-demo"><div className="local-tools-tabs" role="group" aria-label="Preview a local tool"><button aria-pressed={kind==="document"} onClick={()=>setKind("document")}><FileText size={17} /> Document</button><button aria-pressed={kind==="sheet"} onClick={()=>setKind("sheet")}><FileSpreadsheet size={17} /> Spreadsheet</button></div><div className="tool-input"><span>Structured input</span><strong>{kind==="document" ? "Turn these notes into a travel brief" : "Put the trip expenses in a spreadsheet"}</strong><div className="tool-input-tags">{(kind==="document" ? ["Places","Opening hours","Your notes"] : ["Train tickets","Hotel","Local travel"]).map(label=><span key={label}>{label}</span>)}</div></div><div className="tool-connector"><span /><ArrowRight size={18} /><span /></div><div className="tool-output" key={kind}>{kind==="document" ? <><img src={withBasePath("/cutouts/document.webp")} width={320} height={320} alt="" loading="lazy" /><div><strong>weekend-brief.docx</strong><p>Your selected notes,<br />organized into a document.</p><span><Check size={14} /> Sample output</span></div></> : <div className="sheet-output"><strong><FileSpreadsheet size={19} /> trip-expenses.xlsx</strong><table><caption className="sr-only">Sample trip expense data</caption><thead><tr><th>Item</th><th>Amount</th></tr></thead><tbody><tr><td>Train tickets</td><td>₹1,200</td></tr><tr><td>Hotel</td><td>₹3,000</td></tr><tr><td>Local travel</td><td>₹450</td></tr></tbody></table><span>Sample output</span></div>}</div><p className="local-tool-note"><LockKeyhole size={13} /> Sample inputs and outputs for the built-in tools.</p></div></section>;
}
