// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Browser and page operation rows, in appendix order.
//!
//! This is one storage shard of the registry, not a second registry. The
//! public iterator in the parent module preserves the global order.
//!
//! Names the product excludes by requirement, and names a later milestone
//! owns, are present as values. A refusal spelled out in the table is
//! enumerable by a test and visible in review; a refusal expressed by leaving
//! a name out is invisible until somebody adds it back.

use super::super::entry::{
    IdempotencyClass, NameMatch, ToolAvailability, ToolDispatch, ToolEntry, ToolLoading,
};
use super::super::milestone::Milestone;
use super::super::parameters;
use crate::authority::ActionClass;
/// Every registered name, in the order the appendix lists them.
///
/// `browser.form.fill` and `browser.form.submit` are here even though the
/// appendix says they do not exist before the milestone M5 exit review. The
/// name being present is what makes the refusal testable; it carries no
/// authority, and [`resolve`] answers with the milestone that owns it.
pub(super) const ROWS: &[ToolEntry] = &[
    ToolEntry {
        name: "browser.navigate",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::OpenLink),
        terminal_safe: false,
        purpose: "Open an https address in this tab. A new site counts against the sites budget; you are told if it is refused.",
        parameters: parameters::NAVIGATE,
    },
    ToolEntry {
        name: "browser.search",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::OpenLink),
        terminal_safe: false,
        purpose: "Search the web from Taffy's own search tab; use it to find the official site.",
        parameters: parameters::SEARCH,
    },
    ToolEntry {
        name: "browser.back",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ControlTab),
        terminal_safe: false,
        purpose: "Browser-owned back navigation",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "browser.forward",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ControlTab),
        terminal_safe: false,
        purpose: "Browser-owned forward navigation",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "browser.reload",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ControlTab),
        terminal_safe: false,
        purpose: "Reload one exact existing tab",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "browser.stop_loading",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ControlTab),
        terminal_safe: false,
        purpose: "Stop the active load in one exact existing tab",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "browser.tabs.open",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::CreateTaskTab),
        terminal_safe: false,
        purpose: "Open a new tab of your own at an https address, a second site alongside this one.",
        parameters: parameters::TABS_OPEN,
    },
    ToolEntry {
        name: "browser.tabs.list",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "List bounded assistant-owned task tabs",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "browser.tabs.activate",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::MoveFocus),
        terminal_safe: false,
        purpose: "Activate one exact assistant-owned task tab",
        parameters: parameters::TASK_TAB,
    },
    ToolEntry {
        name: "browser.tabs.close",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::CreateTaskTab),
        terminal_safe: false,
        purpose: "Close one exact assistant-owned task tab",
        parameters: parameters::TASK_TAB,
    },
    ToolEntry {
        name: "browser.dom.query",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Filter a fresh whole-document observation by semantic facts",
        parameters: parameters::DOM_QUERY,
    },
    ToolEntry {
        name: "browser.dom.read",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Whole-document observation",
        // The shipping observation request is document-scoped. A node operand
        // would look narrower to policy while being discarded by the browser.
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "browser.dom.click",
        matching: NameMatch::Exact,
        // One press on one exact observed node. The optional expected-state
        // parameter is bound into the durable intent and re-read by the
        // browser verifier; naming it buys a disclosure control's exact check,
        // and leaving it out is an ordinary press the browser verifies by the
        // document moving. Checked, selected and focused outcomes remain on
        // their narrower classes either way.
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::SyntheticClick),
        terminal_safe: false,
        purpose: "Press one exact control on the page",
        parameters: parameters::DOM_ACTIVATE,
    },
    ToolEntry {
        name: "browser.dom.focus",
        matching: NameMatch::Exact,
        // Focus has one fixed observable outcome, so it stays a separate
        // operation rather than borrowing the disclosure activation parser.
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::MoveFocus),
        terminal_safe: false,
        purpose: "Move focus to one exact node and verify the focused state",
        parameters: parameters::NODE,
    },
    ToolEntry {
        name: "browser.link.open",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::OpenLink),
        terminal_safe: false,
        purpose: "Follow a numbered link from the last page snapshot.",
        parameters: parameters::NODE,
    },
    ToolEntry {
        name: "browser.dom.scroll",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::ConditionallyIdempotent,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ScrollIntoView),
        terminal_safe: false,
        purpose: "Bring one exact semantic node into view",
        parameters: parameters::SCROLL,
    },
    ToolEntry {
        name: "browser.form.inspect",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Read-only form schema and state observation",
        parameters: parameters::FORM,
    },
    ToolEntry {
        name: "browser.form.fill",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::Consequential,
        dispatch: ToolDispatch::BrowserAction(ActionClass::FillField),
        terminal_safe: false,
        purpose: "Fill one field with a value the person supplied through user.request_values.",
        parameters: parameters::FORM_FILL,
    },
    ToolEntry {
        name: "browser.form.select",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::Consequential,
        dispatch: ToolDispatch::BrowserAction(ActionClass::SelectOption),
        terminal_safe: false,
        purpose: "Choose an option the browser advertised for one exact field",
        parameters: parameters::FORM_FILL,
    },
    ToolEntry {
        name: "browser.form.toggle",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::Consequential,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ToggleControl),
        terminal_safe: false,
        purpose: "Set one exact toggle to an explicit checked state",
        parameters: parameters::FORM_TOGGLE,
    },
    ToolEntry {
        name: "browser.form.submit",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::Consequential,
        dispatch: ToolDispatch::BrowserAction(ActionClass::SubmitForm),
        terminal_safe: false,
        purpose: "Submit a form with the submit control the page advertised.",
        parameters: parameters::FORM_SUBMIT,
    },
    ToolEntry {
        name: "browser.download.start",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::Consequential,
        dispatch: ToolDispatch::BrowserAction(ActionClass::StartDownload),
        terminal_safe: false,
        purpose: "Start a download from an https address the page offered; the browser verifies the outcome.",
        parameters: parameters::DOWNLOAD_START,
    },
    ToolEntry {
        name: "browser.download.from_link",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::Consequential,
        dispatch: ToolDispatch::BrowserAction(ActionClass::StartDownload),
        terminal_safe: false,
        purpose: "Download the exact observed link; the browser resolves its current address without exposing it.",
        parameters: parameters::NODE,
    },
    ToolEntry {
        name: "browser.download.list",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "List the downloads this task started and their state.",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "browser.download.cancel",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M5),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::IdempotentWrite,
        dispatch: ToolDispatch::BrowserAction(ActionClass::StartDownload),
        terminal_safe: false,
        purpose: "Cancel an exact download previously started by this task",
        parameters: parameters::TASK_DOWNLOAD,
    },
    ToolEntry {
        name: "browser.selection.read",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M3),
        loading: ToolLoading::Immediate,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Read the user's current selection within data scope",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "page.images",
        // The adapters this namespace covers. A row here is a claim that the
        // member exists, not permission to invent one.
        matching: NameMatch::Namespace {
            members: &["page.images.describe", "page.images.read_text"],
        },
        availability: ToolAvailability::From(Milestone::M6),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Image observation and understanding adapters",
        parameters: parameters::NODE,
    },
    ToolEntry {
        name: "page.video.inspect",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M6),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Video and transcript adapter inspection",
        parameters: parameters::NODE,
    },
    ToolEntry {
        name: "page.pdf.inspect",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M4),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Document adapter inspection, basic at M4 and rich at M6",
        parameters: parameters::NONE,
    },
    ToolEntry {
        name: "page.screenshot.inspect",
        matching: NameMatch::Exact,
        availability: ToolAvailability::From(Milestone::M6),
        loading: ToolLoading::Deferred,
        idempotency: IdempotencyClass::PureRead,
        dispatch: ToolDispatch::BrowserAction(ActionClass::ObservePage),
        terminal_safe: false,
        purpose: "Bounded redacted page image fallback when structured adapters are unusable",
        parameters: parameters::NONE,
    },
];
