// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// @generated by taffy-core/contracts/bip/codegen/generate.py — do not edit
// Source of truth: taffy-core/contracts/bip/schema/bip.version.json

#ifndef TAFFY_COMPONENTS_INTELLIGENCE_CONTENT_BIP_SCHEMA_VERSION_H_
#define TAFFY_COMPONENTS_INTELLIGENCE_CONTENT_BIP_SCHEMA_VERSION_H_

namespace taffy {

// The protocol version this build speaks, as it appears in every message's
// schema_version field.
inline constexpr char kBipSchemaVersion[] = "0.14";

}  // namespace taffy

#endif  // TAFFY_COMPONENTS_INTELLIGENCE_CONTENT_BIP_SCHEMA_VERSION_H_
