#!/usr/bin/env python3
# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Generate `crate_sources.gni` from the component-owned Rust crates.

WHY THIS IS GENERATED AND NOT HAND-WRITTEN

GN does not glob, and Chromium's convention is to list every source explicitly
so that adding a file is a visible change in review and a build cannot silently
compile a subset of a crate. That convention assumes the sources and the build
file live together. TaffyGo's crates live in separate owning components and
several GN files consume the same absolute `//taffy` lists. A hand-written list
in each directory does not stay correct; it stays plausible.

So the list is generated from the crates, committed, and checked. `--check` is
the gate: it regenerates into memory and compares byte for byte, so a crate that
gained or lost a file fails the build with a one-line fix instead of compiling
without it. The same shape as `taffy-core/contracts/bip/codegen/generate.py`, for the same
reason.

WHAT IS DELIBERATELY EXCLUDED

A module declared `#[cfg(test)] mod name;` is not compiled into a shipping
build, and its file — and everything beneath it — is left out. The
storage-domain crate under `taffy-core/components/storage/core/rust/` is the
case that matters: its library backend and its database-backed suite are both
test-only, and the library they use is a development dependency. Listing them
would put a second database engine's source into the shipping build graph's
inputs and make the "no test-only dependency ships" claim need an explanation
rather than a proof. Files under a crate's `tests/` directory are integration
tests and are never listed at all — they are the host loop's, run by Cargo.

That exclusion is only as good as the module resolution behind it, which is why
`module_dir` below carries the rule and `--self-test` proves it. Read a `mod`
declaration against the wrong directory and the tool excludes a real file for
the wrong reason while the test file it was aiming at ships — silently, because
both outcomes produce a list a build accepts.

Stdlib only.

    generate_crate_sources.py --write      rewrite crate_sources.gni
    generate_crate_sources.py --check      fail if it is stale
    generate_crate_sources.py --self-test  prove the resolution on a fixture

Exit status: 0 clean, 1 stale or malformed.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile

import crate_layout

#: A `mod name;` declaration together with the attribute lines directly above
#: it. One expression rather than two, because whether a module is `cfg(test)`
#: and whether it names its own file with `#[path]` are two facts carried by
#: the same attribute run — and while two independent patterns read them, a
#: module that was both was excluded by one and added straight back by the
#: other. The inline form `#[cfg(test)] mod tests { ... }` is not matched and
#: must not be: it lives inside a file that does ship.
_MODULE_DECLARATION = re.compile(
    r"(?P<attributes>(?:^[ \t]*#\[[^\]]*\][ \t]*\n)*)"
    r"^[ \t]*(?:pub(?:\([^)]*\))?[ \t]+)?mod[ \t]+(?P<name>[A-Za-z0-9_]+)[ \t]*;",
    re.M,
)

#: Rust modules whose source lives somewhere the module name does not say. The
#: declaration is the source of truth; BUILD.gn must not repeat these paths.
_PATH_ATTRIBUTE = re.compile(r"#\[path\s*=\s*\"([^\"]+)\"\]")

#: The attribute that keeps a module out of a shipping build.
_TEST_ATTRIBUTE = re.compile(r"#\[cfg\(test\)\]")

#: Files pulled in at compile time. GN has to know about them or a changed
#: catalog does not rebuild the crate that embeds it.
_EMBEDDED_FILE = re.compile(r"include_(?:str|bytes)!\s*\(\s*\"([^\"]+)\"\s*\)")

_HEADER = """\
# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# @generated by taffy-core/services/core/tools/generate_crate_sources.py
#             — do not edit
#
# Regenerate:  python3 taffy-core/services/core/tools/generate_crate_sources.py --write
# Verify:      python3 taffy-core/services/core/tools/generate_crate_sources.py --check
#
# Every path below is absolute within //taffy, so each crate's owning BUILD.gn
# can consume the same list. No first-party source is copied or symlinked.
#
# Test-only modules are absent by construction, not by omission: a module
# declared `#[cfg(test)] mod name;` is not compiled into a shipping build, and a
# crate's `tests/` directory belongs to the Cargo host loop. That is the whole
# of the "no test-only source in a shipping target" proof — there is nothing to
# filter at build time because there is nothing in the list.
"""


class Declaration:
    """One `mod name;` and the two attributes that decide where it comes from."""

    def __init__(self, declaring: str, name: str, attributes: str) -> None:
        self.declaring = declaring
        self.name = name
        self.test_only = _TEST_ATTRIBUTE.search(attributes) is not None
        found = _PATH_ATTRIBUTE.search(attributes)
        self.path = found.group(1) if found else None


def module_dir(path: str) -> str:
    """The directory Rust resolves a file's `mod name;` declarations against.

    A crate root and a `mod.rs` own the directory they sit in; every other file
    owns a directory named after itself. So `mod tests;` in `src/ports.rs` names
    `src/ports/tests.rs`, never `src/tests.rs`.

    Reading it as the containing directory is correct for `lib.rs` and `mod.rs`
    and wrong for every other file, which is most of them — and it fails in the
    direction that looks like success. `src/runtime/status.rs` declares
    `#[cfg(test)] mod tests;`; resolved against `src/runtime` that lands on
    `src/runtime/tests.rs`, a real file and a real test module, so something was
    excluded and nothing complained. The file the declaration actually names,
    `src/runtime/status/tests.rs`, shipped.
    """
    directory, name = os.path.split(path)
    if name in ("lib.rs", "main.rs", "mod.rs"):
        return directory
    return os.path.join(directory, name[: -len(".rs")])


def rust_files(directory: str) -> list[str]:
    """Every `.rs` file beneath a directory, resolved and sorted."""
    found = [
        os.path.realpath(os.path.join(root, name))
        for root, _dirs, files in os.walk(directory)
        for name in files
        if name.endswith(".rs")
    ]
    return sorted(found)


def declarations(src_dir: str) -> list[Declaration]:
    """Every module declaration in a crate's `src`, with its attributes."""
    found: list[Declaration] = []
    for path in rust_files(src_dir):
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        for match in _MODULE_DECLARATION.finditer(text):
            found.append(
                Declaration(path, match.group("name"), match.group("attributes"))
            )
    return found


def declared_file(declaration: Declaration) -> str | None:
    """The file a module declaration names, or None when there is no such file.

    `#[path]` on a declaration at the top level of a file is relative to that
    file's own directory rather than to its module directory; a plain `mod`
    resolves against the module directory in either of Rust's two spellings.
    """
    if declaration.path is not None:
        candidate = os.path.join(
            os.path.dirname(declaration.declaring), declaration.path
        )
        return os.path.realpath(candidate) if os.path.isfile(candidate) else None
    directory = module_dir(declaration.declaring)
    for candidate in (
        os.path.join(directory, f"{declaration.name}.rs"),
        os.path.join(directory, declaration.name, "mod.rs"),
    ):
        if os.path.isfile(candidate):
            return os.path.realpath(candidate)
    return None


def module_subtree(path: str) -> set[str]:
    """A module's own file and every file beneath it.

    Excluding one file is not excluding a module. `storage-domain`'s
    `src/tests/mod.rs` has five children; leaving those listed puts the whole
    database-backed suite into the shipping graph's inputs while the file that
    declares it is absent — which reads, in the generated list, as if someone
    had taken the module out on purpose.
    """
    return {path} | set(rust_files(module_dir(path)))


def crate_sources(crate_path: str, src_dir: str) -> set[str]:
    """Every file that is part of one crate's shipping build.

    The union of what is on disk and what a `#[path]` declaration reaches comes
    first, and the test-only exclusions come last. The other order lets a module
    that is both `#[cfg(test)]` and `#[path]` be excluded and then added back by
    the second pass, which is not a hypothetical shape:
    `core-runtime`'s `production/persistence/journal.rs` declares exactly one.
    """
    sources = set(rust_files(src_dir))
    excluded: set[str] = set()
    for declaration in declarations(src_dir):
        target = declared_file(declaration)
        if target is None:
            if declaration.path is not None:
                raise SystemExit(
                    f"{crate_path} declares a module that does not exist: "
                    f"{declaration.path} in {declaration.declaring}"
                )
            continue
        if declaration.path is not None:
            sources.add(target)
        if declaration.test_only:
            excluded |= module_subtree(target)
    return sources - excluded


def embedded_files(src_dir: str) -> set[str]:
    """Absolute paths of files reached by `include_str!` or `include_bytes!`."""
    embedded: set[str] = set()
    for path in rust_files(src_dir):
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        for relative in _EMBEDDED_FILE.findall(text):
            embedded.add(os.path.realpath(os.path.join(os.path.dirname(path), relative)))
    return embedded


def gn_source_path(repo_root: str, path: str) -> str:
    """Normalizes one source beneath `taffy-core` to its `//taffy` path."""
    product_root = os.path.realpath(os.path.join(repo_root, "taffy-core"))
    resolved = os.path.realpath(path)
    if os.path.commonpath((product_root, resolved)) != product_root:
        raise SystemExit(f"shipping Rust source is outside taffy-core: {resolved}")
    return f"//taffy/{os.path.relpath(resolved, product_root)}"


def crate_facts(repo_root: str, crate: crate_layout.Crate) -> tuple[list[str], list[str]]:
    """Absolute //taffy (sources, inputs) for one component-owned crate."""
    crate_dir = os.path.realpath(crate_layout.source_dir(repo_root, crate))
    src_dir = os.path.join(crate_dir, "src")
    if not os.path.isdir(src_dir):
        raise SystemExit(f"{crate.path} has no src directory")

    sources = [
        gn_source_path(repo_root, path)
        for path in crate_sources(crate.path, src_dir)
    ]

    inputs = []
    for path in embedded_files(src_dir):
        if not os.path.isfile(path):
            raise SystemExit(f"{crate.path} embeds a file that does not exist: {path}")
        inputs.append(gn_source_path(repo_root, path))

    return sorted(sources), sorted(inputs)


def render(repo_root: str) -> str:
    lines = [_HEADER]
    for crate in crate_layout.SHIPPING_CRATES:
        sources, inputs = crate_facts(repo_root, crate)
        variable = "taffy_" + crate.variable
        prefix = crate_layout.gn_source_prefix(repo_root, crate)
        lines.append("")
        lines.append(f"{variable}_crate_root = \"{prefix}/src/lib.rs\"")
        lines.append("")
        lines.append(f"{variable}_sources = [")
        lines.extend(f'  "{source}",' for source in sources)
        lines.append("]")
        if inputs:
            lines.append("")
            lines.append(f"# Embedded at compile time with include_str! or include_bytes!.")
            lines.append(f"{variable}_inputs = [")
            lines.extend(f'  "{item}",' for item in inputs)
            lines.append("]")
    return "\n".join(lines) + "\n"


def output_path(repo_root: str) -> str:
    return os.path.join(
        crate_layout.service_core_dir(repo_root), "crate_sources.gni"
    )


#: A crate laid out to break every resolution mistake this tool has made. Each
#: entry is one file and the text it holds; the shape, not the size, is the
#: point:
#:
#:   `a.rs` and `a/b.rs` both declare a `#[cfg(test)] mod tests;`, so a resolver
#:   that reads the containing directory instead of the module directory lands
#:   `a/b.rs`'s declaration on `a/tests.rs` — a real file, and the wrong one —
#:   while `a/b/tests.rs` ships;
#:   `a/tests.rs` and `fixtures/mod.rs` both have children, so a resolver that
#:   excludes one file rather than one module leaves those children shipping;
#:   `d.rs` declares a module that is both `#[cfg(test)]` and `#[path]`, so a
#:   resolver that reads the two attributes separately puts it back after taking
#:   it out.
#:
#: `a.rs` spells its declaration `pub(crate) mod tests;` on purpose: that
#: spelling was invisible to the pattern this one replaced, which read only
#: `mod` and `pub mod`.
_FIXTURE = {
    "src/lib.rs": (
        'mod a;\nmod d;\n\n#[rustfmt::skip]\n#[path = "../generated/wire.rs"]\n'
        "mod generated;\n\n#[cfg(test)]\nmod fixtures;\n"
    ),
    "src/a.rs": "mod b;\n\n#[cfg(test)]\npub(crate) mod tests;\n",
    "src/a/b.rs": "pub mod c;\n\n#[cfg(test)]\nmod tests;\n",
    "src/a/b/c.rs": "pub const C: u8 = 0;\n",
    "src/a/b/tests.rs": "#[test]\nfn nested() {}\n",
    "src/a/tests.rs": "mod cases;\n",
    "src/a/tests/cases.rs": "#[test]\nfn case() {}\n",
    "src/d.rs": '#[cfg(test)]\n#[path = "d_tests.rs"]\nmod tests;\n',
    "src/d_tests.rs": "#[test]\nfn relocated() {}\n",
    "src/fixtures/mod.rs": "mod helper;\n",
    "src/fixtures/helper.rs": "pub fn helper() {}\n",
    "generated/wire.rs": "pub struct Wire;\n",
}

#: What the fixture ships, relative to its crate directory. Everything else in
#: `_FIXTURE` is test-only, reached only from a test-only module, or both.
_FIXTURE_SOURCES = {
    "src/lib.rs",
    "src/a.rs",
    "src/a/b.rs",
    "src/a/b/c.rs",
    "src/d.rs",
    "generated/wire.rs",
}


def self_test() -> int:
    """Prove the resolution on a crate written to expose the mistakes."""
    with tempfile.TemporaryDirectory() as crate_dir:
        for relative, text in _FIXTURE.items():
            path = os.path.join(crate_dir, relative)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(text)

        root = os.path.realpath(crate_dir)
        shipping = {
            os.path.relpath(path, root)
            for path in crate_sources("fixture", os.path.join(root, "src"))
        }
        if shipping != _FIXTURE_SOURCES:
            for name in sorted(shipping - _FIXTURE_SOURCES):
                print(f"self-test: {name} ships and must not", file=sys.stderr)
            for name in sorted(_FIXTURE_SOURCES - shipping):
                print(f"self-test: {name} does not ship and must", file=sys.stderr)
            return 1

    print(
        "crate sources: a nested module resolves against its own directory, an "
        "excluded module takes its subtree with it, and #[cfg(test)] applies to a "
        "#[path] module"
    )
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo-root", help="TaffyGo repository root")
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true")
    action.add_argument("--check", action="store_true")
    action.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)

    if args.self_test:
        return self_test()

    try:
        repo_root = crate_layout.resolve_repo_root(args.repo_root)
    except crate_layout.ContractError as error:
        print(f"crate sources: {error}", file=sys.stderr)
        return 1

    generated = render(repo_root)
    target = output_path(repo_root)

    if args.write:
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(generated)
        print(f"crate sources: wrote {os.path.relpath(target, repo_root)}")
        return 0

    if not os.path.exists(target):
        print(f"crate sources: {os.path.relpath(target, repo_root)} does not exist; "
              "run with --write", file=sys.stderr)
        return 1
    with open(target, encoding="utf-8") as handle:
        committed = handle.read()
    if committed != generated:
        print(
            f"crate sources: {os.path.relpath(target, repo_root)} is stale. A crate "
            "gained or lost a source file. Run:\n"
            "    python3 taffy-core/services/core/tools/"
            "generate_crate_sources.py --write",
            file=sys.stderr,
        )
        return 1
    print("crate sources: crate_sources.gni matches the crates")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
