#!/usr/bin/env python3
# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Where the contract lives and what the generator writes.

Authority boundary: paths and the two vocabulary constants that appear in
generated headers. Nothing here reads a file or renders a line — every other
module in this package asks this one where things are, so a directory move is
one edit.
"""

from __future__ import annotations

import os


CODEGEN_DIR = os.path.dirname(os.path.abspath(__file__))
CONTRACT_DIR = os.path.dirname(CODEGEN_DIR)
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(CONTRACT_DIR)))

SCHEMA_DIR = os.path.join(CONTRACT_DIR, "schema")
GOLDEN_DIR = os.path.join(CONTRACT_DIR, "golden")
COMPAT_DIR = os.path.join(CONTRACT_DIR, "compat")
VERSION_FILE = os.path.join(SCHEMA_DIR, "bip.version.json")

RUST_OUT_DIR = os.path.join(CONTRACT_DIR, "rust", "bip-types", "src", "generated")
CXX_VERSION_OUT = os.path.join(
    REPO_ROOT,
    "taffy-core",
    "components",
    "intelligence",
    "content",
    "bip_schema_version.h",
)

#: Hand-written C++ that restates the protocol version, and the pattern that
#: finds the literal in each one.
#:
#: There is one, and it is not a generated file, so ``--check`` cannot compare
#: it byte for byte the way it compares the others. It exists because
#: ``taffy-core/renderer/DEPS`` bars the renderer from every path that carries
#: the generated constant: ``-taffy/common/public`` is an authority boundary
#: with a stated reason, and the generated header lives under the browser's
#: ``components/intelligence/content``. Until the constant is emitted somewhere
#: the renderer may legitimately include, the renderer keeps its own copy and
#: this table is what keeps that copy honest.
#:
#: This exists because the copy went stale and nothing noticed. The renderer
#: advertised 0.11 while the contract reached 0.13, and because
#: ``ProtocolNegotiator::OnProtocolInfo`` refuses any reply whose version is not
#: this build's own, every protocol negotiation in every binary answered
#: UNSUPPORTED — in the product as well as in the tests, for two minor steps.
VERSION_RESTATEMENTS = {
    os.path.join(
        REPO_ROOT, "taffy-core", "renderer", "page_intelligence_endpoint.cc"
    ): r'constexpr\s+char\s+kProtocolVersion\[\]\s*=\s*"([^"]*)"\s*;',
}

#: The marker every generated file carries in its first lines. The repository's
#: file-discipline gate detects generated output by it, so changing the wording
#: changes what that gate measures.
GENERATED_MARK = "@generated by taffy-core/contracts/bip/codegen/generate.py — do not edit"

#: Wrap width for generated documentation comments.
DOC_WIDTH = 96


class GeneratorError(Exception):
    """The schema asks for something the generator will not guess at."""


def relative(path: str) -> str:
    """A repository-relative path, for a message a person reads.

    Separators are normalised to ``/`` so a finding printed on Windows and the
    same finding printed on Linux are the same string, which is what lets a
    generated file's own header be compared byte for byte across hosts.
    """
    return os.path.relpath(path, REPO_ROOT).replace(os.sep, "/")
