// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Why an artifact could not be generated.
//!
//! A closed enumeration. Each member is a refusal the generator makes rather
//! than a degradation it accepts: an externally derived fact with no locator
//! is refused, not exported uncited, and an artifact past its size limit is
//! refused, not truncated.
/// Why an artifact could not be generated.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ArtifactError {
    /// There is nothing to export.
    NoFacts,
    /// An externally derived fact has no provenance locator.
    UncitedFact {
        /// The fact, as text, for a local diagnostic.
        fact_id: String,
    },
    /// A locator cites a source that is not in the request.
    UnknownSource {
        /// The source, as text, for a local diagnostic.
        source_id: String,
    },
    /// The generated artifact is larger than the task's budget allows.
    TooLarge {
        /// How large it would be.
        bytes: u64,
        /// What the budget allows.
        limit: u64,
    },
    /// A rich format was accidentally sent to the inert Markdown/CSV engine.
    ///
    /// The portable task lifecycle names all formats, but only `file-engine`
    /// may encode XLSX, PDF, DOCX, or PPTX. Refusing here makes a missing
    /// adapter fail closed rather than producing a mislabeled text file.
    RichFormatRequiresFileEngine,
    /// Media bytes already exist behind a browser-owned descriptor.
    ///
    /// They may be exported through trusted browser custody, but must never be
    /// regenerated by the portable text renderer.
    BrowserCustodiedFormat,
}

impl ArtifactError {
    /// A short, compiled-in name, safe to record in an audit event.
    pub const fn label(&self) -> &'static str {
        match self {
            Self::NoFacts => "no_facts",
            Self::UncitedFact { .. } => "uncited_fact",
            Self::UnknownSource { .. } => "unknown_source",
            Self::TooLarge { .. } => "too_large",
            Self::RichFormatRequiresFileEngine => "rich_format_requires_file_engine",
            Self::BrowserCustodiedFormat => "browser_custodied_format",
        }
    }
}
