#!/usr/bin/env python3
# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Validate and project TaffyGo design tokens without third-party packages."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "tokens.json"
OUTPUTS = {
    ROOT
    / "generated/kotlin/com/taffygo/browser/ui/core/designsystem/internal/GeneratedTaffyPalette.kt":
        "kotlin",
    ROOT / "generated/css/taffy-color-tokens.css": "css",
    ROOT / "generated/cpp/taffy_color_tokens.h": "cpp",
}
THEMES = ("light", "dark")
TRANSLUCENT = {
    "accentWash",
    "dangerWash",
    "positiveWash",
    "privateTintWash",
    "ribbonOneWash",
    "ribbonTwoWash",
    "ribbonThreeWash",
    "scrim",
    "selection",
}
TOKEN_NAME = re.compile(r"[a-z][A-Za-z0-9]*\Z")
ARGB = re.compile(r"[0-9A-F]{8}\Z")


@dataclass(frozen=True)
class Tokens:
    order: tuple[str, ...]
    themes: dict[str, dict[str, str]]


#: The licence notice every generated projection carries. The wording after
#: the copyright line is Exhibit A of the Mozilla Public License and is not
#: editable (decision 0205); it is spelled out here rather than imported
#: because a generator's inputs are declared to GN and an import across the
#: tree is an input nothing declares.
NOTICE = (
    "Copyright (c) 2026 Matterward Labs Private Limited.",
    "",
    "This Source Code Form is subject to the terms of the Mozilla Public",
    "License, v. 2.0. If a copy of the MPL was not distributed with this",
    "file, You can obtain one at https://mozilla.org/MPL/2.0/.",
)


def notice(marker: str) -> list[str]:
    """The notice in one comment syntax."""
    return [f"{marker} {line}".rstrip() for line in NOTICE]


def load(path: Path = SOURCE) -> Tokens:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read {path}: {error}") from error
    findings: list[str] = []
    if document.get("schema_version") != 1:
        findings.append("schema_version must be 1")
    if document.get("format") != "argb32":
        findings.append("format must be argb32")
    order_value = document.get("token_order")
    order = tuple(order_value) if isinstance(order_value, list) else ()
    if not order:
        findings.append("token_order must be a non-empty array")
    if len(order) != len(set(order)):
        findings.append("token_order contains a duplicate")
    for name in order:
        if not isinstance(name, str) or not TOKEN_NAME.fullmatch(name):
            findings.append(f"invalid lowerCamel token name: {name!r}")
    themes_value = document.get("themes")
    themes = themes_value if isinstance(themes_value, dict) else {}
    if tuple(themes) != THEMES:
        findings.append(f"themes must be ordered exactly as {list(THEMES)}")
    expected = set(order)
    for theme in THEMES:
        values = themes.get(theme)
        if not isinstance(values, dict):
            findings.append(f"{theme} must be an object")
            continue
        actual = set(values)
        for missing in sorted(expected - actual):
            findings.append(f"{theme} is missing {missing}")
        for extra in sorted(actual - expected):
            findings.append(f"{theme} has unknown token {extra}")
        for name in order:
            value = values.get(name)
            if not isinstance(value, str) or not ARGB.fullmatch(value):
                findings.append(f"{theme}.{name} must be eight upper-case ARGB hex digits")
                continue
            alpha = value[:2]
            if name in TRANSLUCENT and alpha == "FF":
                findings.append(f"{theme}.{name} must remain translucent")
            if name not in TRANSLUCENT and alpha != "FF":
                findings.append(f"{theme}.{name} must remain opaque")
    if findings:
        raise ValueError("\n".join(findings))
    return Tokens(order=order, themes=themes)


def upper_camel(name: str) -> str:
    return name[0].upper() + name[1:]


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)([A-Z])", r"-\1", name).lower()


def css_color(argb: str) -> str:
    alpha, rgb = argb[:2], argb[2:]
    return f"#{rgb.lower()}" if alpha == "FF" else f"#{rgb.lower()}{alpha.lower()}"


def render_kotlin(tokens: Tokens) -> str:
    lines = [
        *notice("//"),
        "//",
        "// Generated by //taffy/resources/tokens/generate.py. Do not edit.",
        "package com.taffygo.browser.ui.core.designsystem.internal",
        "",
        "internal object GeneratedTaffyPalette {",
    ]
    for theme in THEMES:
        lines.append(f"    val {theme}: PaletteValues = PaletteValues(")
        for name in tokens.order:
            lines.append(f"        {name} = 0x{tokens.themes[theme][name]},")
        lines.append("    )")
        if theme != THEMES[-1]:
            lines.append("")
    lines.extend(("}", ""))
    return "\n".join(lines)


def render_css(tokens: Tokens) -> str:
    def block(selector: str, theme: str) -> list[str]:
        result = [f"{selector} {{"]
        for name in tokens.order:
            result.append(
                f"  --taffy-{kebab(name)}: {css_color(tokens.themes[theme][name])};"
            )
        result.append("}")
        return result

    lines = ["/*", *NOTICE, "*/", "",
             "/* Generated by //taffy/resources/tokens/generate.py. Do not edit. */"]
    lines.extend(block(':root, [data-taffy-theme="light"]', "light"))
    lines.append("")
    lines.extend(block('[data-taffy-theme="dark"]', "dark"))
    lines.append("")
    lines.append("@media (prefers-color-scheme: dark) {")
    for line in block(":root:not([data-taffy-theme])", "dark"):
        lines.append(f"  {line}")
    lines.extend(("}", ""))
    return "\n".join(lines)


def render_cpp(tokens: Tokens) -> str:
    count = len(tokens.order)
    lines = [
        *notice("//"),
        "//",
        "// Generated by //taffy/resources/tokens/generate.py. Do not edit.",
        "#ifndef TAFFY_RESOURCES_TOKENS_GENERATED_CPP_TAFFY_COLOR_TOKENS_H_",
        "#define TAFFY_RESOURCES_TOKENS_GENERATED_CPP_TAFFY_COLOR_TOKENS_H_",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace taffy::resources {",
        "",
        "enum class ColorToken : std::size_t {",
    ]
    for name in tokens.order:
        lines.append(f"  k{upper_camel(name)},")
    lines.extend(("  kCount,", "};", "", f"using ColorPalette = std::array<std::uint32_t, {count}>;", ""))
    for theme in THEMES:
        name = "kLightColorPalette" if theme == "light" else "kDarkColorPalette"
        lines.append(f"inline constexpr ColorPalette {name} = {{")
        for token in tokens.order:
            lines.append(f"    0x{tokens.themes[theme][token]}u,")
        lines.extend(("};", ""))
    lines.extend(
        (
            "constexpr std::uint32_t ResolveColor(const ColorPalette& palette,",
            "                                     ColorToken token) {",
            "  return palette[static_cast<std::size_t>(token)];",
            "}",
            "",
            "}  // namespace taffy::resources",
            "",
            "#endif  // TAFFY_RESOURCES_TOKENS_GENERATED_CPP_TAFFY_COLOR_TOKENS_H_",
            "",
        )
    )
    return "\n".join(lines)


def projections(tokens: Tokens) -> dict[Path, str]:
    renderers = {"kotlin": render_kotlin, "css": render_css, "cpp": render_cpp}
    return {path: renderers[kind](tokens) for path, kind in OUTPUTS.items()}


BUILD_GN = ROOT / "BUILD.gn"
_GN_LABEL_ROOT = "//taffy/resources/tokens/"
_GN_LIST = re.compile(r"(taffy_design_token_\w+)\s*=\s*\[([^\]]*)\]", re.DOTALL)
_GN_STRING = re.compile(r'"([^"]+)"')


def _declared_in_build_gn() -> dict[str, set[str]]:
    """Return the GN metadata lists, keyed by their metadata name."""
    text = BUILD_GN.read_text(encoding="utf-8")
    return {
        name: set(_GN_STRING.findall(body)) for name, body in _GN_LIST.findall(text)
    }


def check_build_gn_manifest() -> list[str]:
    """Hold `BUILD.gn`'s design-token metadata against this generator.

    The metadata is a hand-written list of GN labels and OUTPUTS is the list
    the generator actually writes. Nothing else compares them, so without this
    a fourth projection would be emitted, compiled by Gradle (which mounts the
    whole generated Kotlin directory), and silently absent from the product
    graph's manifest.
    """
    findings: list[str] = []
    try:
        declared = _declared_in_build_gn()
    except OSError:
        return [f"missing {BUILD_GN.name} beside the generator"]
    expected = {
        "taffy_design_token_source": {
            _GN_LABEL_ROOT + SOURCE.relative_to(ROOT).as_posix()
        },
        "taffy_design_token_projections": {
            _GN_LABEL_ROOT + path.relative_to(ROOT).as_posix() for path in OUTPUTS
        },
    }
    for name, wanted in expected.items():
        found = declared.get(name)
        if found is None:
            findings.append(f"{BUILD_GN.name} declares no {name}")
            continue
        for label in sorted(wanted - found):
            findings.append(f"{BUILD_GN.name} {name} is missing {label}")
        for label in sorted(found - wanted):
            findings.append(f"{BUILD_GN.name} {name} names {label}, which nothing generates")
    return findings


def check(tokens: Tokens) -> list[str]:
    findings: list[str] = check_build_gn_manifest()
    for path, expected in projections(tokens).items():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            findings.append(f"missing generated projection: {path.relative_to(ROOT)}")
            continue
        if actual != expected:
            findings.append(f"stale generated projection: {path.relative_to(ROOT)}")
    return findings


def write(tokens: Tokens) -> None:
    for path, contents in projections(tokens).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")


def self_test() -> int:
    original = json.loads(SOURCE.read_text(encoding="utf-8"))
    cases = []
    missing = json.loads(json.dumps(original))
    del missing["themes"]["dark"][missing["token_order"][0]]
    cases.append(missing)
    opaque_wash = json.loads(json.dumps(original))
    opaque_wash["themes"]["light"]["accentWash"] = "FFE8AA4E"
    cases.append(opaque_wash)
    for index, document in enumerate(cases):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "tokens.json"
            path.write_text(json.dumps(document), encoding="utf-8")
            try:
                load(path)
            except ValueError:
                continue
            print(f"token generator self-test case {index} was not rejected", file=sys.stderr)
            return 1
    print(f"token generator: {len(cases)} mutation cases rejected")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    try:
        tokens = load()
    except ValueError as error:
        print(f"token generator: {error}", file=sys.stderr)
        return 1
    if args.write:
        write(tokens)
        print(f"token generator: wrote {len(OUTPUTS)} projections")
        return 0
    findings = check(tokens)
    if findings:
        for finding in findings:
            print(f"token generator: {finding}", file=sys.stderr)
        return 1
    print(f"token generator: {len(tokens.order)} tokens, {len(OUTPUTS)} projections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
