// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package org.chromium.taffy.host

import org.chromium.base.test.BaseRobolectricTestRunner
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test
import org.junit.runner.RunWith
import taffy.core_api.MAX_IDENTIFIER_BYTES

/** Fail-closed bounds for the exact provider-auth identity reply. */
@RunWith(BaseRobolectricTestRunner::class)
class CoreApiPersonalizationOperationsTest {

    @Test
    fun `only nonempty identifiers within the generated byte limit pass`() {
        val atLimit = "f".repeat(MAX_IDENTIFIER_BYTES)

        assertNull(validatedProviderAuthFlowId(null))
        assertNull(validatedProviderAuthFlowId(""))
        assertEquals(atLimit, validatedProviderAuthFlowId(atLimit))
        assertNull(validatedProviderAuthFlowId("f".repeat(MAX_IDENTIFIER_BYTES + 1)))
    }

    @Test
    fun `the generated limit counts utf8 bytes rather than characters`() {
        val twoByteCharacter = "é"
        val atLimit = twoByteCharacter.repeat(MAX_IDENTIFIER_BYTES / 2)
        val overLimit = twoByteCharacter.repeat(MAX_IDENTIFIER_BYTES / 2 + 1)

        assertEquals(MAX_IDENTIFIER_BYTES, atLimit.encodeToByteArray().size)
        assertEquals(atLimit, validatedProviderAuthFlowId(atLimit))
        assertNull(validatedProviderAuthFlowId(overLimit))
    }
}
