// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

/// The four closed output formats owned by this module.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Format {
    /// Office Open XML workbook.
    Xlsx,
    /// Office Open XML word-processing document.
    Docx,
    /// Office Open XML presentation.
    Pptx,
    /// Portable Document Format 1.7 document.
    Pdf,
}

impl Format {
    /// Exact MIME type for Android document custody.
    pub const fn mime_type(self) -> &'static str {
        match self {
            Self::Xlsx => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            Self::Docx => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            Self::Pptx => {
                "application/vnd.openxmlformats-officedocument.presentationml.presentation"
            }
            Self::Pdf => "application/pdf",
        }
    }

    /// Extension without a leading dot.
    pub const fn extension(self) -> &'static str {
        match self {
            Self::Xlsx => "xlsx",
            Self::Docx => "docx",
            Self::Pptx => "pptx",
            Self::Pdf => "pdf",
        }
    }
}

/// A spreadsheet cell. Formula cells are deliberately unrepresentable.
#[derive(Clone, Debug, PartialEq)]
pub enum Cell {
    /// An absent cell.
    Blank,
    /// Literal inline text, including text beginning with `=`, `+`, `-`, or `@`.
    Text(String),
    /// A finite IEEE-754 value.
    Number(f64),
    /// A boolean value.
    Boolean(bool),
}

/// One named worksheet.
#[derive(Clone, Debug, PartialEq)]
pub struct Sheet {
    /// Human-visible name, unique case-insensitively within the workbook.
    pub name: String,
    /// Rows in document order.
    pub rows: Vec<Vec<Cell>>,
}

/// A workbook specification.
#[derive(Clone, Debug, PartialEq)]
pub struct Workbook {
    /// Document title stored in fixed core properties.
    pub title: String,
    /// One or more worksheets.
    pub sheets: Vec<Sheet>,
}

/// One document block.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Block {
    /// A paragraph of text.
    Paragraph(String),
    /// A level 1 through 6 heading.
    Heading {
        /// Heading level.
        level: u8,
        /// Heading text.
        text: String,
    },
    /// A rectangular or ragged table of literal text cells.
    Table(Vec<Vec<String>>),
}

/// A word-processing document specification.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Document {
    /// Document title.
    pub title: String,
    /// Blocks in document order.
    pub blocks: Vec<Block>,
}

/// One presentation slide.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Slide {
    /// Slide title.
    pub title: String,
    /// Literal body lines.
    pub body: Vec<String>,
}

/// A presentation specification.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Deck {
    /// Presentation title.
    pub title: String,
    /// One or more slides.
    pub slides: Vec<Slide>,
}

/// One PDF page.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PdfPage {
    /// Literal text lines in top-to-bottom order.
    pub lines: Vec<String>,
}

/// A PDF specification.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PdfDocument {
    /// Document title stored in the Info dictionary.
    pub title: String,
    /// One or more pages.
    pub pages: Vec<PdfPage>,
}

/// One closed typed request.
#[derive(Clone, Debug, PartialEq)]
pub enum FileSpec {
    /// Generate XLSX.
    Workbook(Workbook),
    /// Generate DOCX.
    Document(Document),
    /// Generate PPTX.
    Deck(Deck),
    /// Generate PDF.
    Pdf(PdfDocument),
}

impl FileSpec {
    /// Format implied by the request variant.
    pub const fn format(&self) -> Format {
        match self {
            Self::Workbook(_) => Format::Xlsx,
            Self::Document(_) => Format::Docx,
            Self::Deck(_) => Format::Pptx,
            Self::Pdf(_) => Format::Pdf,
        }
    }
}

/// Structural facts proven by validation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Validation {
    /// Validated format.
    pub format: Format,
    /// Final byte length.
    pub byte_len: usize,
    /// ZIP package part count, or PDF indirect object count.
    pub structural_parts: usize,
    /// Sheets, document body, slides, or pages proven present.
    pub logical_units: usize,
}

/// Generated bytes returned only after structural validation succeeds.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    format: Format,
    bytes: Vec<u8>,
    validation: Validation,
}

impl GeneratedFile {
    pub(crate) fn new(format: Format, bytes: Vec<u8>, validation: Validation) -> Self {
        Self {
            format,
            bytes,
            validation,
        }
    }

    /// File format.
    pub const fn format(&self) -> Format {
        self.format
    }

    /// Exact MIME type.
    pub const fn mime_type(&self) -> &'static str {
        self.format.mime_type()
    }

    /// Exact extension without a leading dot.
    pub const fn extension(&self) -> &'static str {
        self.format.extension()
    }

    /// Validated immutable bytes.
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Consume the wrapper and transfer byte ownership.
    pub fn into_bytes(self) -> Vec<u8> {
        self.bytes
    }

    /// Structural proof produced before return.
    pub const fn validation(&self) -> Validation {
        self.validation
    }
}
