// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The entrypoint registry this build was compiled with.
//!
//! @generated by `taffy-core/components/tools/entrypoints/tools/generate_entrypoints.py`
//! - do not edit.
//!
//! Its source is `entrypoints/source/entrypoints.json`. Add an entrypoint by
//! adding a row there and running the generator with `--write`.

use super::registry::{Entrypoint, NativePath, NativeState, Port};

/// A digest of the rows below, so one registry can be told from another.
pub const REGISTRY_FINGERPRINT: u32 = 1_879_083_464;

/// The revision of the registry's own shape.
pub const REGISTRY_VERSION: u32 = 1;

/// Every kind a declared input or output may carry.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ValueKind {
    /// One Office Open XML text document, produced by the worker and returned as bytes.
    DocumentDocx,
    /// One bounded UTF-8 JSON document whose shape the entrypoint's own reader fixes. It names no file, no origin and no handle.
    JsonUtf8,
    /// One Office Open XML workbook, produced by the worker and returned as bytes. Nothing is written to a disk the worker can see, because it can see none.
    SpreadsheetXlsx,
    /// Bounded UTF-8 comma-separated rows with a header row. The bytes are data, never a formula and never a reference to another cell.
    TableCsvUtf8,
}

impl ValueKind {
    /// The name this kind is written with in the registry source.
    #[must_use]
    pub const fn wire_name(self) -> &'static str {
        match self {
            Self::DocumentDocx => "document-docx",
            Self::JsonUtf8 => "json-utf8",
            Self::SpreadsheetXlsx => "spreadsheet-xlsx",
            Self::TableCsvUtf8 => "table-csv-utf8",
        }
    }
}

static NATIVE_CORE_TABLE_RESHAPE: NativePath = NativePath::new(
    "core.table.reshape",
    NativeState::Active,
    "Selecting, ordering, grouping and pivoting rows is arithmetic over a bounded table. The portable core owns it, in Rust, in a process that already exists and that a person's data already crosses.",
);

static INPUTS_DOCUMENT_BUILD: &[Port] = &[
    Port::new(
        "document",
        ValueKind::JsonUtf8,
        true,
        "The described document: its sections, their headings and their paragraphs.",
    ),
];

static OUTPUTS_DOCUMENT_BUILD: &[Port] = &[
    Port::new(
        "document",
        ValueKind::DocumentDocx,
        true,
        "The composed document as bytes.",
    ),
];

static INPUTS_SPREADSHEET_BUILD: &[Port] = &[
    Port::new(
        "workbook",
        ValueKind::JsonUtf8,
        true,
        "The described workbook: its sheets, their column headings and their formats.",
    ),
    Port::new(
        "rows",
        ValueKind::TableCsvUtf8,
        true,
        "The cell values, already reshaped, one table per named sheet.",
    ),
];

static OUTPUTS_SPREADSHEET_BUILD: &[Port] = &[
    Port::new(
        "spreadsheet",
        ValueKind::SpreadsheetXlsx,
        true,
        "The composed workbook as bytes.",
    ),
];

static INPUTS_TABLE_RESHAPE: &[Port] = &[
    Port::new(
        "rows",
        ValueKind::TableCsvUtf8,
        true,
        "The table to reshape.",
    ),
    Port::new(
        "recipe",
        ValueKind::JsonUtf8,
        true,
        "The described reshaping: which columns survive, in what order, grouped by what.",
    ),
];

static OUTPUTS_TABLE_RESHAPE: &[Port] = &[
    Port::new(
        "rows",
        ValueKind::TableCsvUtf8,
        true,
        "The reshaped table.",
    ),
];

/// Every entrypoint, in ascending identity order.
pub static ENTRYPOINTS: &[Entrypoint] = &[
    Entrypoint::new(
        "document.build",
        "Compose one text document from a described outline and return its bytes.",
        None,
        INPUTS_DOCUMENT_BUILD,
        OUTPUTS_DOCUMENT_BUILD,
    ),
    Entrypoint::new(
        "spreadsheet.build",
        "Compose one workbook from tables and a described layout, and return its bytes.",
        None,
        INPUTS_SPREADSHEET_BUILD,
        OUTPUTS_SPREADSHEET_BUILD,
    ),
    Entrypoint::new(
        "table.reshape",
        "Select, order, group and pivot the rows of one bounded table.",
        Some(&NATIVE_CORE_TABLE_RESHAPE),
        INPUTS_TABLE_RESHAPE,
        OUTPUTS_TABLE_RESHAPE,
    ),
];
