// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The content-free baseline for one browser-bound task effect.

use core_runtime::{wire, TaskId};

use crate::ffi;

pub(super) fn empty_binding(
    task_id: &TaskId,
    ordinal: u32,
    effect_id: String,
    operation: wire::OperationEnvelope,
) -> ffi::BridgeTaskEffect {
    ffi::BridgeTaskEffect {
        operation: ffi::BridgeOperation {
            operation_id: operation.operation_id,
            service_generation: operation.service_generation,
            task_revision: operation.task_revision,
            deadline_monotonic_ms: operation.deadline_monotonic_ms,
            idempotency_key: operation.idempotency_key,
        },
        effect_id,
        task_id: task_id.as_str().to_owned(),
        ordinal,
        kind: 0,
        principal_id: String::new(),
        action_id: String::new(),
        action_class: 0,
        action_operation: 0,
        canonical_intent: Vec::new(),
        proposal_digest: String::new(),
        action_idempotency_key: String::new(),
        tab_id: String::new(),
        has_node_id: false,
        node_id: String::new(),
        field_values_companion_node_ids: Vec::new(),
        principal: 0,
        data_classes: Vec::new(),
        context_risk: 0,
        has_approval: false,
        approval_receipt_id: String::new(),
        approval_expires_at_monotonic_ms: 0,
        approval_expires_at_utc_ms: 0,
        approval_browser_session_id: String::new(),
        control_mode: 0,
        policy_version: 0,
        capability_id: String::new(),
        dispatch_id: String::new(),
        frame_id: String::new(),
        page_epoch: String::new(),
        graph_revision: 0,
        normalized_origin: String::new(),
        has_opaque_origin_id: false,
        opaque_origin_id: String::new(),
        tool_name: String::new(),
        has_destination_origin: false,
        destination_origin: String::new(),
        has_destination_address: false,
        destination_address: String::new(),
        has_operand_handle: false,
        operand_handle: String::new(),
        has_transient_search_query: false,
        transient_search_query: String::new(),
        has_task_tab_binding: false,
        task_tab_browser_session_id: String::new(),
        has_task_tab_target: false,
        task_tab_target_tab_id: String::new(),
        task_tab_target_frame_id: String::new(),
        task_tab_target_page_epoch: String::new(),
        task_tab_target_graph_revision: 0,
        has_task_download_binding: false,
        task_download_browser_session_id: String::new(),
        task_download_id: String::new(),
        has_task_store_binding: false,
        task_store_has_query: false,
        task_store_query: String::new(),
        task_store_limit: 0,
        has_policy_discovery: false,
        policy_discovery_tab_id: String::new(),
        policy_discovery_browser_session_id: String::new(),
        policy_discovery_remaining_new_source_cap: 0,
        action_input_kind: wire::TaskActionInputKind::None as u8,
        has_supplied_value: false,
        supplied_value_request_id: String::new(),
        supplied_value_index: 0,
        has_toggle_state: false,
        toggle_checked: false,
        preconditions: Vec::new(),
        postcondition: 0,
        request_id: String::new(),
        permission: 0,
        deadline_monotonic_ms: 0,
        deadline_utc_ms: 0,
        permission_browser_session_id: String::new(),
        handover_id: String::new(),
        handover_window_ms: 0,
        call_id: String::new(),
        route_id: String::new(),
        model_id: String::new(),
        disclosure: 0,
        wire_api: 0,
        provider_id: String::new(),
        endpoint: String::new(),
        endpoint_kind: 0,
        request_body: Vec::new(),
        static_header_names: Vec::new(),
        static_header_values: Vec::new(),
        max_output_bytes: 0,
        not_before_monotonic_ms: 0,
        has_credential_handle: false,
        credential_handle: String::new(),
        has_media_attachment: false,
        media_attachment_handle: String::new(),
        media_attachment_mime_type: String::new(),
        discovery_bootstrap_browser_session_id: String::new(),
        discovery_bootstrap_remaining_new_source_cap: 0,
        settlement_kind: 0,
        recovery_rule: 0,
        artifact_kind: 0,
        artifact_id: String::new(),
        artifact_workspace_revision: 0,
        artifact_content: Vec::new(),
        observation_scope: 0,
        observation_max_bytes: 0,
        observation_max_nodes: 0,
        observation_max_text_bytes: 0,
        observation_max_frames: 0,
        observation_deadline_ms: 0,
        job_id: String::new(),
        tool_runtime: 0,
        has_python_job: false,
        python_entrypoint: String::new(),
        python_input: Vec::new(),
        has_media_job: false,
        media_operation: 0,
        media_source_id: String::new(),
        media_source_browser_session_id: String::new(),
        media_source_bytes: 0,
        media_max_frames: 0,
    }
}
