// Copyright (c) 2026 Matterward Labs Private Limited.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package com.taffygo.browser.ui.core.task

import com.taffygo.browser.ui.core.common.FailureReason
import com.taffygo.browser.ui.core.common.TaffyResult
import com.taffygo.browser.ui.core.model.TaskControl
import com.taffygo.browser.ui.core.model.TaskTemplate
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.emptyFlow
import taffy.core_api.TaskArtifactKind

/** Profile-scoped task commands and immutable state from the generated Core API. */
interface TaskRepository {
    val state: StateFlow<TaskRepositoryState>

    /**
     * Names the task the surfaces should follow, or null to follow whichever
     * is under way. A composer calls this with the id that appeared after its
     * start was admitted; the default does nothing, which is the right answer
     * for a repository that holds one task at most.
     */
    fun follow(taskId: String?) = Unit

    /**
     * Hides one task that has ended from the surfaces, on this device, until
     * the next start.
     *
     * A task that fails is final for the rest of the browser run: the core
     * still publishes it, the bar still shows its red pill, and no command at
     * any seam retires it. This is residency, not retirement — the session
     * stays held with whatever it is still owed (decision 0149 clause 5), and
     * a filter can only ever show less than the core published, so it cannot
     * reach the bindings that clause 8 protects. A running task is never
     * hidden; the way out of a pause is Resume.
     */
    fun putAway(taskId: String) = Unit

    /** No replay: only the live explicit request receives generated bytes. */
    val artifactExports: Flow<TaskArtifactPayload>
        get() = emptyFlow()

    suspend fun startTask(
        goal: String,
        template: TaskTemplate,
        consent: TaskConsentIntent,
        workspaceId: String? = null,
    ): TaffyResult<Unit>

    /** Starts from one explicit page-bound saved-skill offer, if selected. */
    suspend fun startTask(
        goal: String,
        template: TaskTemplate,
        consent: TaskConsentIntent,
        workspaceId: String?,
        skillOfferId: String?,
    ): TaffyResult<Unit> =
        if (skillOfferId == null) {
            startTask(goal, template, consent, workspaceId)
        } else {
            TaffyResult.Failure(FailureReason.INVALID_REQUEST)
        }

    suspend fun cancelTask(taskId: String): TaffyResult<Unit>

    /** Submit one control already present in the exact projected task revision. */
    suspend fun useControl(
        taskId: String,
        taskRevision: ULong,
        control: TaskControl,
    ): TaffyResult<Unit> =
        if (control == TaskControl.STOP) {
            cancelTask(taskId)
        } else {
            TaffyResult.Failure(FailureReason.INVALID_REQUEST)
        }

    suspend fun completeHandover(taskId: String): TaffyResult<Unit>

    suspend fun supplyUserInput(taskId: String, answer: String): TaffyResult<Unit>

    /**
     * Ask a finished task something more (decision 0137).
     *
     * The words go to the core as the next turn of the task's own
     * conversation and are never journaled; the repository remembers them
     * beside the answer that follows, for this process only. The default
     * refuses, which is the right answer for a repository that cannot carry a
     * conversation: a composer reading the refusal starts afresh.
     */
    suspend fun followUp(taskId: String, question: String): TaffyResult<Unit> =
        TaffyResult.Failure(FailureReason.INVALID_REQUEST)

    suspend fun approveAction(taskId: String, actionId: String): TaffyResult<Unit>

    /** Explicitly keep one exact generated artifact before it may leave the browser. */
    suspend fun acceptTaskArtifact(taskId: String, artifactId: String): TaffyResult<Unit> =
        TaffyResult.Failure(FailureReason.INVALID_REQUEST)

    /** Ask for transient bytes only after the current snapshot says the artifact is kept. */
    suspend fun requestTaskArtifactExport(
        requestId: String,
        taskId: String,
        artifactId: String,
        kind: TaskArtifactKind,
    ): TaffyResult<Unit> = TaffyResult.Failure(FailureReason.INVALID_REQUEST)

    /** Explicitly keep the current terminal task result at its exact workspace revision. */
    suspend fun saveWorkspace(workspaceId: String, workspaceRevision: ULong): TaffyResult<Unit> =
        TaffyResult.Failure(FailureReason.INVALID_REQUEST)

    /** Explicitly discard one terminal temporary workspace at its exact revision. */
    suspend fun discardWorkspace(
        workspaceId: String,
        workspaceRevision: ULong,
    ): TaffyResult<Unit> = TaffyResult.Failure(FailureReason.INVALID_REQUEST)

    suspend fun retryCore(): TaffyResult<Unit>
}
