# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""The frozen bytes of a payload, and the one flag that may replace them.

A golden payload is only evidence if it is an input. The Core API fixture used
to be regenerated by `--write` and then compared against the expression that
had just written it, so a change to the wire layout moved both sides together
and the gate stayed green for exactly the change it existed to catch. What is
frozen here is a file the generator reads and never writes on the ordinary
path: `--check` re-encodes the golden document and requires the committed bytes
back, and `--refreeze` is the only way to replace them — refused unless the
codec's `schema_version` and the contract's version were both raised in the
same change.

Decoding the committed bytes matters as much as re-encoding them. Re-encoding
proves today's writer still produces yesterday's bytes; decoding proves today's
reader still understands them, which is the promise a device with an existing
journal is relying on.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import payload_codec
from contract_schema import CONTRACT_ROOT, ContractError
from fixture_documents import load_document


def _entries(ledger: dict[str, Any]) -> dict[str, dict[str, str]]:
    frozen = ledger.get("frozen_payloads", {})
    if not isinstance(frozen, dict):
        raise ContractError("the ledger's frozen_payloads must be an object")
    return frozen


def expected_bytes(
    contract: str, schema: dict[str, Any], models: dict[str, Any], name: str, entry: dict[str, str]
) -> bytes:
    """The bytes the golden document encodes to under today's layout."""
    model = models.get(name)
    if model is None:
        raise ContractError(f"{contract}: frozen payload {name} names no declared codec")
    source = load_document(CONTRACT_ROOT / contract / entry["source"])
    try:
        return payload_codec.encode(model, source)
    except payload_codec.CodecRefusal as refusal:
        raise ContractError(
            f"{contract}: the golden document for {name} does not encode: {refusal.error}"
        ) from refusal
    except (AttributeError, KeyError, TypeError) as error:
        # A golden document that does not match the record it claims to be is a
        # defect in the fixture, not a crash in the generator; say which field.
        raise ContractError(
            f"{contract}: the golden document for {name} does not match the schema: {error}"
        ) from error


def committed_bytes(contract: str, entry: dict[str, str]) -> bytes:
    path = CONTRACT_ROOT / contract / entry["bytes"]
    try:
        text = path.read_text(encoding="utf-8").strip()
    except OSError as error:
        raise ContractError(f"missing frozen payload {path}: {error}") from error
    try:
        return bytes.fromhex(text)
    except ValueError as error:
        raise ContractError(f"{path}: frozen payload is not hexadecimal") from error


def stale_payloads(
    contract: str, ledger: dict[str, Any], schema: dict[str, Any], models: dict[str, Any]
) -> dict[str, bytes]:
    """Frozen files whose bytes no longer match the golden document."""
    stale: dict[str, bytes] = {}
    for name, entry in _entries(ledger).items():
        expected = expected_bytes(contract, schema, models, name, entry)
        if expected != committed_bytes(contract, entry):
            stale[name] = expected
    return stale


def audit(
    contract: str, ledger: dict[str, Any], schema: dict[str, Any], models: dict[str, Any]
) -> None:
    """Fail unless every frozen payload still round-trips through this build."""
    for name, entry in _entries(ledger).items():
        data = committed_bytes(contract, entry)
        verdict, error = payload_codec.verdict(models[name], data)
        if verdict != "ACCEPT":
            raise ContractError(
                f"{contract}: the frozen {name} payload no longer decodes ({error}). "
                f"A build that cannot read its own frozen bytes cannot read a device's."
            )
    stale = stale_payloads(contract, ledger, schema, models)
    if stale:
        raise ContractError(
            f"{contract}: the frozen bytes for {sorted(stale)[0]} are not what this build "
            "encodes. If the wire layout really changed, raise the codec's schema_version "
            "and the contract version and run --refreeze; otherwise the change to the "
            "layout is the defect."
        )


def codec_bump_refusals(
    ledger: dict[str, Any], models: dict[str, Any], names: list[str]
) -> list[str]:
    """Why `--refreeze` may not replace these frozen bytes, if it may not."""
    recorded = ledger.get("codec_schema_versions", {})
    refusals: list[str] = []
    for name in sorted(names):
        frozen_version = recorded.get(name)
        if frozen_version is None or models[name]["schema_version"] <= frozen_version:
            refusals.append(
                f"--refreeze will not replace the frozen {name} bytes while its "
                f"schema_version is still {frozen_version}. Every device journal written "
                "by the old layout would decode under the new one without a word."
            )
    return refusals


def require_codec_bump(
    contract: str, ledger: dict[str, Any], models: dict[str, Any], stale: dict[str, bytes]
) -> None:
    """Refuse to replace frozen bytes at a schema version that never moved."""
    refusals = codec_bump_refusals(ledger, models, sorted(stale))
    if refusals:
        raise ContractError(f"{contract}: " + "\n  ".join(refusals))


def write(contract: str, ledger: dict[str, Any], stale: dict[str, bytes]) -> list[Path]:
    written: list[Path] = []
    for name, data in stale.items():
        path = CONTRACT_ROOT / contract / _entries(ledger)[name]["bytes"]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(data.hex() + "\n", encoding="utf-8")
        written.append(path)
    return written
