# Copyright (c) 2026 Matterward Labs Private Limited.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""The three projections of a frozen entrypoint registry.

One accepted document in, three artifacts out: the browser's C++ table, the
sandboxed core's Rust table, and the readable one. Nothing here validates -
`entrypoint_source.py` has already refused anything these renderers could not
express - and nothing here reads or writes a file.
"""

from __future__ import annotations

import json
import re

from entrypoint_source import NATIVE_STATES, fingerprint

#: The licence notice every generated projection carries, one line per entry
#: so each renderer can prefix it with its own comment marker. The wording
#: after the copyright line is Exhibit A of the Mozilla Public License and is
#: not editable (decision 0205).
NOTICE = (
    "Copyright (c) 2026 Matterward Labs Private Limited.",
    "",
    "This Source Code Form is subject to the terms of the Mozilla Public",
    "License, v. 2.0. If a copy of the MPL was not distributed with this",
    "file, You can obtain one at https://mozilla.org/MPL/2.0/.",
)


def notice_lines(marker: str) -> list[str]:
    """The notice in one comment syntax, ready to splice into a projection."""
    return [f"{marker} {line}".rstrip() for line in NOTICE]


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def camel(value: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[-_.]", value))


def upper_snake(value: str) -> str:
    return re.sub(r"[^A-Z0-9]", "_", value.upper())



def render_rust(document: dict) -> str:
    lines = [
        *notice_lines("//"),
        "",
        "//! The entrypoint registry this build was compiled with.",
        "//!",
        "//! @generated by "
        "`taffy-core/components/tools/entrypoints/tools/generate_entrypoints.py`",
        "//! - do not edit.",
        "//!",
        "//! Its source is `entrypoints/source/entrypoints.json`. Add an entrypoint by",
        "//! adding a row there and running the generator with `--write`.",
        "",
        "use super::registry::{Entrypoint, NativePath, NativeState, Port};",
        "",
        "/// A digest of the rows below, so one registry can be told from another.",
        f"pub const REGISTRY_FINGERPRINT: u32 = {fingerprint(document):_};",
        "",
        "/// The revision of the registry's own shape.",
        f"pub const REGISTRY_VERSION: u32 = {document['registry_version']};",
        "",
        "/// Every kind a declared input or output may carry.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]",
        "pub enum ValueKind {",
    ]
    for kind in document["value_kinds"]:
        lines.append(f"    /// {kind['description']}")
        lines.append(f"    {camel(kind['name'])},")
    lines.append("}")
    lines.append("")
    lines.append("impl ValueKind {")
    lines.append("    /// The name this kind is written with in the registry source.")
    lines.append("    #[must_use]")
    lines.append("    pub const fn wire_name(self) -> &'static str {")
    lines.append("        match self {")
    for kind in document["value_kinds"]:
        lines.append(f"            Self::{camel(kind['name'])} => {rust_string(kind['name'])},")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    for path in document["native_paths"]:
        name = "NATIVE_" + upper_snake(path["id"])
        lines.append(f"static {name}: NativePath = NativePath::new(")
        lines.append(f"    {rust_string(path['id'])},")
        lines.append(f"    NativeState::{camel(path['state'])},")
        lines.append(f"    {rust_string(path['description'])},")
        lines.append(");")
        lines.append("")

    for row in document["entrypoints"]:
        for key in ("inputs", "outputs"):
            name = f"{key.upper()}_{upper_snake(row['id'])}"
            lines.append(f"static {name}: &[Port] = &[")
            for port in row[key]:
                lines.append("    Port::new(")
                lines.append(f"        {rust_string(port['name'])},")
                lines.append(f"        ValueKind::{camel(port['kind'])},")
                lines.append(f"        {str(port.get('required', True)).lower()},")
                lines.append(f"        {rust_string(port['description'])},")
                lines.append("    ),")
            lines.append("];")
            lines.append("")

    lines.append("/// Every entrypoint, in ascending identity order.")
    lines.append("pub static ENTRYPOINTS: &[Entrypoint] = &[")
    for row in document["entrypoints"]:
        alternative = row["native_alternative"]
        native = f"Some(&NATIVE_{upper_snake(alternative)})" if alternative else "None"
        lines.append("    Entrypoint::new(")
        lines.append(f"        {rust_string(row['id'])},")
        lines.append(f"        {rust_string(row['summary'])},")
        lines.append(f"        {native},")
        lines.append(f"        INPUTS_{upper_snake(row['id'])},")
        lines.append(f"        OUTPUTS_{upper_snake(row['id'])},")
        lines.append("    ),")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def render_cpp(document: dict) -> str:
    guard = "TAFFY_COMPONENTS_TOOLS_ENTRYPOINTS_GENERATED_CPP_TOOL_ENTRYPOINTS_H_"
    lines = [
        *notice_lines("//"),
        "//",
        "// @generated by taffy-core/components/tools/entrypoints/tools/",
        "//             generate_entrypoints.py - do not edit",
        "//",
        "// The frozen entrypoint registry as the browser compiles it in. Every name a",
        "// sandboxed worker may ever be asked for is below; there is no loader, no",
        "// path, and no way to add a row without shipping a build.",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        '#include "base/containers/span.h"',
        "",
        "namespace taffy::tools {",
        "",
        "// Every kind a declared input or output may carry.",
        "enum class ToolValueKind {",
    ]
    for kind in document["value_kinds"]:
        lines.append(f"  // {kind['description']}")
        lines.append(f"  k{camel(kind['name'])},")
    lines.append("};")
    lines.append("")
    lines.append("// Whether the native owner of a refused entrypoint is built today.")
    lines.append("enum class ToolNativeState {")
    for state in NATIVE_STATES:
        lines.append(f"  k{camel(state)},")
    lines.append("};")
    lines.append("")
    lines.extend(
        [
            "// One declared input or output. Trivially copyable and constexpr, so the",
            "// whole table lives in read-only memory and no run-time construction of one",
            "// is possible.",
            "struct ToolEntrypointPort {",
            "  std::string_view name;",
            "  ToolValueKind kind;",
            "  bool required;",
            "  std::string_view description;",
            "};",
            "",
            "// The native owner of a capability the Python runtime is refused.",
            "struct ToolNativePath {",
            "  std::string_view id;",
            "  ToolNativeState state;",
            "  std::string_view description;",
            "};",
            "",
            "// One registry row. `native_alternative` is empty when no native owner is",
            "// declared; a non-empty one is what refuses the entrypoint.",
            "//",
            "// The ports are spans rather than a pointer and a count, so a reader cannot",
            "// index past the end of one - the pair form is two facts a caller has to keep",
            "// in step, and Chromium's unsafe-buffer diagnostic refuses it for that reason.",
            "struct ToolEntrypoint {",
            "  std::string_view id;",
            "  std::string_view summary;",
            "  std::string_view native_alternative;",
            "  base::span<const ToolEntrypointPort> inputs;",
            "  base::span<const ToolEntrypointPort> outputs;",
            "};",
            "",
        ]
    )
    lines.append("// A digest of the rows below, so one registry can be told from another.")
    lines.append(f"inline constexpr uint32_t kToolRegistryFingerprint = {fingerprint(document)}u;")
    lines.append("")
    lines.append("// The revision of the registry's own shape.")
    lines.append(f"inline constexpr uint32_t kToolRegistryVersion = {document['registry_version']}u;")
    lines.append("")

    for path in document["native_paths"]:
        name = "kNative" + camel(path["id"])
        lines.append(f"inline constexpr ToolNativePath {name} = {{")
        lines.append(f"    {json.dumps(path['id'])},")
        lines.append(f"    ToolNativeState::k{camel(path['state'])},")
        lines.append(f"    {json.dumps(path['description'])},")
        lines.append("};")
        lines.append("")

    lines.append("inline constexpr std::array<ToolNativePath, "
                 f"{len(document['native_paths'])}> kToolNativePaths = {{{{")
    for path in document["native_paths"]:
        lines.append(f"    kNative{camel(path['id'])},")
    lines.append("}};")
    lines.append("")

    for row in document["entrypoints"]:
        for key in ("inputs", "outputs"):
            name = f"k{camel(key)}{camel(row['id'])}"
            lines.append(
                f"inline constexpr std::array<ToolEntrypointPort, {len(row[key])}> {name} = {{{{"
            )
            for port in row[key]:
                required = "true" if port.get("required", True) else "false"
                lines.append(
                    f"    {{{json.dumps(port['name'])}, ToolValueKind::k{camel(port['kind'])}, "
                    f"{required},"
                )
                lines.append(f"     {json.dumps(port['description'])}}},")
            lines.append("}};")
            lines.append("")

    lines.append("// Every entrypoint, in ascending identity order.")
    lines.append(
        f"inline constexpr std::array<ToolEntrypoint, {len(document['entrypoints'])}> "
        "kToolEntrypoints = {{"
    )
    for row in document["entrypoints"]:
        lines.append(f"    {{{json.dumps(row['id'])},")
        lines.append(f"     {json.dumps(row['summary'])},")
        lines.append(f"     {json.dumps(row['native_alternative'])},")
        lines.append(f"     k{camel('inputs')}{camel(row['id'])},")
        lines.append(f"     k{camel('outputs')}{camel(row['id'])}}},")
    lines.append("}};")
    lines.append("")
    lines.append("}  // namespace taffy::tools")
    lines.append("")
    lines.append(f"#endif  // {guard}")
    lines.append("")
    return "\n".join(lines)


def render_doc(document: dict) -> str:
    lines = [
        "# The frozen tool-entrypoint registry",
        "",
        "**Status:** `[Proposed]` — generated from",
        "`../../source/entrypoints.json` by",
        "`../../tools/generate_entrypoints.py`. Do not edit this file; edit the source",
        "and run the generator with `--write`.",
        "",
        "This is the complete list of things a sandboxed worker may ever be asked to",
        "do. A name that is not below is refused before a process is spent on it, and",
        "no row can be added except by shipping a build — the rules and the reasoning",
        # A decision is cited by number, never linked: the design records
        # stay out of the public tree, and the exporter refuses to rewrite a
        # generated file, so a link here would fail both trees' gates.
        "are in [the registry's README](../../README.md) and decision 0064.",
        "",
        f"Registry version {document['registry_version']}; fingerprint "
        f"`{fingerprint(document)}`; {len(document['entrypoints'])} entrypoints.",
        "",
        "## Entrypoints",
        "",
        "| Entrypoint | What it does | Admitted? |",
        "|---|---|---|",
    ]
    for row in document["entrypoints"]:
        alternative = row["native_alternative"]
        verdict = (
            f"Refused — `{alternative}` owns it" if alternative else "Admitted"
        )
        lines.append(f"| `{row['id']}` | {row['summary']} | {verdict} |")
    lines.append("")

    for row in document["entrypoints"]:
        lines.append(f"### `{row['id']}`")
        lines.append("")
        lines.append(row["summary"])
        lines.append("")
        if row["native_alternative"]:
            lines.append(
                f"**Refused for the Python runtime.** `{row['native_alternative']}` is the "
                "native owner of this capability, so the core answers the request there and "
                "never starts a worker for it."
            )
            lines.append("")
        lines.append("| Direction | Name | Kind | Required | What it is |")
        lines.append("|---|---|---|---|---|")
        for port in row["inputs"]:
            required = "yes" if port.get("required", True) else "no"
            lines.append(
                f"| input | `{port['name']}` | `{port['kind']}` | {required} | "
                f"{port['description']} |"
            )
        for port in row["outputs"]:
            lines.append(
                f"| output | `{port['name']}` | `{port['kind']}` | — | {port['description']} |"
            )
        lines.append("")

    lines.append("## Value kinds")
    lines.append("")
    lines.append("| Kind | What it carries |")
    lines.append("|---|---|")
    for kind in document["value_kinds"]:
        lines.append(f"| `{kind['name']}` | {kind['description']} |")
    lines.append("")

    lines.append("## Native owners")
    lines.append("")
    lines.append(
        "A row here is why an entrypoint above is refused. `planned` means the native "
        "owner is not built yet — the refusal still stands, because the question the "
        "registry answers is which layer owns a capability, not which layer has "
        "finished it."
    )
    lines.append("")
    lines.append("| Native owner | State | Why it owns this |")
    lines.append("|---|---|---|")
    for path in document["native_paths"]:
        lines.append(f"| `{path['id']}` | {path['state']} | {path['description']} |")
    lines.append("")
    return "\n".join(lines)


